### ISSUE TITLE
Refactor Validation and Server side code

### ISSUE THREAD

**Issue by mathanraj0601** [Aryainguz/Euphoria-Check-PERMA-Meter-Express#29]
### Task :

- [ ] Refactor the validation logic for the result to improve code readability and maintainability.
- [ ] Implement standardized email validation using the Zod library better validation practices.
- [ ] Introduce global exception handling for Node.js and Express.js to handle errors uniformly across the application.
- [ ] Identify and move hardcoded strings to a separate file/constants file to centralize string management and enhance localization support.

**Comment by mathanraj0601** [comment]
Hi @Aryainguz .This is the continuation of issue #15 

Could you kindly assign me to SWOC 24?

**Comment by Aryainguz** [comment]
@mathanraj0601 go ahead 🚀

**Comment by mathanraj0601** [comment]
That great @Aryainguz  : )

**Comment by mathanraj0601** [comment]
Absolutely, @Aryainguz! 😊 I was thinking it might be more convenient for everyone if I create separate PRs for each task. This way, it'll be easier to review and manage. What do you think?
